title: Deep Search Pages
email: anony.impl@example.com
description: >-
  Deep Search Pages 个人博客主页 - 探索技术、艺术与生活的交汇点

baseurl: ""
url: "https://anony-impl.github.io"

twitter_username: anony_impl
github_username: anony-impl

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
